version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080 # replace with OpenFaaS gateway address
functions:
  splited:
    lang: python3-flask
    handler: ../functions/splited 
    image: radvin1356/splited

  count_of_pattern:
    lang: python3-flask
    handler: ../functions/count_of_pattern
    image: radvin1356/count_of_pattern

  remove:
    lang: python3-flask
    handler: ../functions/remove 
    image: radvin1356/remove


